[pytest]
testpaths = tests
python_files = test_*.py
addopts = --strict-markers

markers =
    basic: mark a test as a basic playwright test.
    search: mark a test as a search playwright test.
    login: mark a test as a login playwright test.
